baseurl: '/greemta'
exclude: ['README.md']
permalink: pretty
title: 'Greemta'

google_analytics_id: ""
homepage:
  show_call_box: false
  tell_me_more: true
logo:
  mobile: "images/logo/logo-mobile.svg"
  desktop: "images/logo/logo.svg"
  desktop_height: "20px"
footer:
  copyright_text: 'CC-BY'

seo:
  meta_og_title: "Greemta"
  meta_og_type: "website"
  meta_og_url: "https://greemta.eu"
  meta_og_image: "https://raw.githubusercontent.com/zerostaticthemes/jekyll-serif-theme/master/screenshots/tn.png"
  meta_og_description: "Greemta challenge"
  meta_twitter_card: "summary"
  meta_twitter_site: "@greemta"
  meta_twitter_creator: "@greemta"

collections:
  contents:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
